name: lld
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - brotli-python=1.0.9
  - ca-certificates=2021.5.30
  - certifi=2021.5.30
  - click=8.0.1
  - dash=1.20.0
  - dash-core-components=1.16.0
  - dash-html-components=1.1.3
  - dash-renderer=1.9.1
  - dash-table=4.11.3
  - dataclasses=0.8
  - flask=2.0.1
  - flask-compress=1.10.1
  - future=0.18.2
  - itsdangerous=2.0.1
  - jinja2=3.0.1
  - ld_impl_linux-64=2.35.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=9.3.0
  - libgfortran5=9.3.0
  - libgomp=9.3.0
  - liblapack=3.9.0
  - libopenblas=0.3.15
  - libstdcxx-ng=9.3.0
  - markupsafe=2.0.1
  - ncurses=6.2
  - numpy=1.20.3
  - openssl=1.1.1k
  - pandas=1.2.4
  - pip=21.1.2
  - plotly=4.14.3
  - python=3.9.4
  - python-dateutil=2.8.1
  - python_abi=3.9
  - pytz=2021.1
  - pyyaml=5.4.1
  - readline=8.1
  - retrying=1.3.3
  - setuptools=49.6.0
  - six=1.16.0
  - sqlite=3.35.5
  - tk=8.6.10
  - tzdata=2021a
  - werkzeug=2.0.1
  - wheel=0.36.2
  - xz=5.2.5
  - yaml=0.2.5
  - zlib=1.2.11
